# Generated by Django 5.2.17 on 2026-09-28 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
    ]
