# Generated by Django 5.2.17 on 2026-09-27 18:14

import django.db.models.deletion
import pacientes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='nombre completo')),
                ('fecha_nacimiento', models.DateField(validators=[pacientes.validators.validar_fecha_nacimiento], verbose_name='fecha de nacimiento')),
                ('rut', models.CharField(max_length=12, validators=[pacientes.validators.validar_rut], verbose_name='RUT')),
                ('telefono', models.CharField(max_length=20, verbose_name='teléfono')),
                ('motivo_consulta', models.TextField(verbose_name='motivo de consulta')),
                ('experiencia_previa', models.TextField(blank=True, help_text='Tratamientos o atenciones anteriores relacionados con la solicitud.', verbose_name='experiencia previa')),
                ('antecedentes_personales', models.TextField(blank=True, verbose_name='antecedentes de salud personales')),
                ('antecedentes_familiares', models.TextField(blank=True, verbose_name='antecedentes de salud familiares')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('DERIVADA', 'Derivada')], default='PENDIENTE', max_length=10, verbose_name='estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='administracion.especialidad', verbose_name='especialidad')),
            ],
            options={
                'verbose_name': 'solicitud',
                'verbose_name_plural': 'solicitudes',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado', 'fecha_creacion'], name='pacientes_s_estado_9df12b_idx'), models.Index(fields=['especialidad', 'estado'], name='pacientes_s_especia_01987e_idx')],
            },
        ),
    ]
