# Generated by Django 5.2.17 on 2026-09-27 18:24

import pacientes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='rut',
            field=models.CharField(help_text='Se guarda siempre formateado como 12345678-5.', max_length=12, validators=[pacientes.validators.validar_rut], verbose_name='RUT'),
        ),
    ]
