# Generated by Django 5.2.17 on 2026-09-29 19:16

import encrypted_model_fields.fields
import pacientes.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_solicitud_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='antecedentes_familiares',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, verbose_name='antecedentes de salud familiares'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='antecedentes_personales',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, verbose_name='antecedentes de salud personales'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='rut',
            field=encrypted_model_fields.fields.EncryptedCharField(help_text='Se guarda siempre formateado como 12345678-5.', validators=[pacientes.validators.validar_rut], verbose_name='RUT'),
        ),
    ]
