"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================
# Tasks 45/46: Lectura de variables de entorno desde .env.
# Se inicializa acá arriba (no pegado a DATABASES como antes)
# para que esté disponible para cualquier configuración del
# archivo que la necesite, incluyendo ALLOWED_HOSTS.
# ============================================
env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zsuuijoci2map%f187-n*^%q4#%m0wxix+$*_+7f&h!zkt#ga*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps del proyecto
    'pacientes',
    'coordinacion',
    'estudiantes',
    'administracion',
    'seguridad',
    # ============================================
    # Task 31: Proteger datos sensibles del formulario (REQ-08)
    # Librería de cifrado transparente de campos en la BD.
    # Usa Fernet (AES-128 + HMAC) internamente.
    # ============================================

    'encrypted_model_fields',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# ============================================
# Task 23:
# Reemplaza el bloque DATABASES que Django genera por
# defecto (que apunta a SQLite) para que en vez de eso
# se conecte a la base de datos MySQL real del proyecto.
# ============================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': env('DB_PORT', default='3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


# Task 30: el sistema es para Chile; con esto los mensajes de
# validación del formulario salen en español y las horas en hora local.
LANGUAGE_CODE = 'es-cl'
TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


# ============================================
# Task 31: Proteger datos sensibles del formulario
# Issue padre: REQ-08 (Cifrado de datos sensibles)
# --------------------------------------------
# Llave de cifrado Fernet. Se lee desde el .env
# (nunca hardcodeada). Si falta, la app falla al
# arrancar: mejor fallar fuerte que cifrar mal.
# ============================================
FIELD_ENCRYPTION_KEY = env('FIELD_ENCRYPTION_KEY')


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# # ============================================
# # Task 35: Redirecciones para autenticación y RBAC
# # ============================================
# LOGIN_URL = 'login'
# LOGIN_REDIRECT_URL = '/'
# LOGOUT_REDIRECT_URL = 'login'


# ============================================
# Task 42: Redirecciones de autenticación y RBAC
# --------------------------------------------
# Las URLs de login/logout están registradas en
# seguridad/urls.py con app_name = "seguridad".
# Por eso se referencian con el namespace "seguridad:".
# Sin esto, Django lanza NoReverseMatch al resolver
# {% url 'login' %} o al redirigir tras el logout.
# ============================================
LOGIN_URL = 'seguridad:login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'seguridad:login'


# ============================================
# Tasks 45 y 46: Seguridad de la conexión (REQ-09)
# Se activan SOLO cuando DEBUG=False, porque
# http://127.0.0.1:8000 no tiene certificado SSL.
# SECURE_PROXY_SSL_HEADER es necesario porque Azure App
# Service termina el certificado SSL en su balanceador,
# no en el propio proceso de Django.
# Pendiente de verificar en un entorno real desplegado
# (ver riesgo abierto de Task 38).
# ============================================
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True